spring.application.name=glassapp

# ===============================
# = Server config
# ===============================
server.port=8080

# ===============================
# = Datasource (H2 in-memory)
# ===============================
spring.datasource.url=jdbc:h2:mem:glassdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# ===============================
# = JPA / Hibernate
# ===============================
# T? ??ng t?o/?i?u ch?nh schema (create, update, validate, none)
spring.jpa.hibernate.ddl-auto=update

# Hi?n th? SQL trong console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# = H2 Console
# ===============================
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
